/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.billabear.sdk.api;

import com.billabear.sdk.model.Error;
import java.io.File;
import com.billabear.sdk.model.InlineResponse20014;
import com.billabear.sdk.model.InlineResponse2006;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for InvoicesApi
 */
@Ignore
public class InvoicesApiTest {

    private final InvoicesApi api = new InvoicesApi();

    /**
     * Charge Invoice
     *
     * Attempts to charge a card that is on file for the invoice amount
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void chargeInvoiceTest() throws Exception {
        String invoiceId = null;
        InlineResponse20014 response = api.chargeInvoice(invoiceId);

        // TODO: test validations
    }
    /**
     * Download Invoice
     *
     * Returns the pdf blob for the invoice
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void downloadInvoiceTest() throws Exception {
        String invoiceId = null;
        File response = api.downloadInvoice(invoiceId);

        // TODO: test validations
    }
    /**
     * List Customer Invoices
     *
     * List Customer Invoices
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getInvoicesForCustomerTest() throws Exception {
        String customerId = null;
        InlineResponse2006 response = api.getInvoicesForCustomer(customerId);

        // TODO: test validations
    }
}
