/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.billabear.sdk.api;

import com.billabear.sdk.model.Error;
import java.io.File;
import com.billabear.sdk.model.InlineResponse20014;
import com.billabear.sdk.model.InlineResponse2004;
import com.billabear.sdk.model.InlineResponse2006;
import com.billabear.sdk.model.InlineResponse2009;
import com.billabear.sdk.model.IssueRefundPayment;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for PaymentsApi
 */
@Ignore
public class PaymentsApiTest {

    private final PaymentsApi api = new PaymentsApi();

    /**
     * Charge Invoice
     *
     * Attempts to charge a card that is on file for the invoice amount
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void chargeInvoiceTest() throws Exception {
        String invoiceId = null;
        InlineResponse20014 response = api.chargeInvoice(invoiceId);

        // TODO: test validations
    }
    /**
     * Download Invoice
     *
     * Returns the pdf blob for the invoice
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void downloadInvoiceTest() throws Exception {
        String invoiceId = null;
        File response = api.downloadInvoice(invoiceId);

        // TODO: test validations
    }
    /**
     * Download Receipt
     *
     * Returns the pdf blob for the Receipt
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void downloadReceiptTest() throws Exception {
        String receipt = null;
        File response = api.downloadReceipt(receipt);

        // TODO: test validations
    }
    /**
     * List Customer Invoices
     *
     * List Customer Invoices
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getInvoicesForCustomerTest() throws Exception {
        String customerId = null;
        InlineResponse2006 response = api.getInvoicesForCustomer(customerId);

        // TODO: test validations
    }
    /**
     * List Customer Payments
     *
     * List Customer Payment
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getPaymentsForCustomerTest() throws Exception {
        String customerId = null;
        Integer limit = null;
        String lastKey = null;
        String name = null;
        InlineResponse2004 response = api.getPaymentsForCustomer(customerId, limit, lastKey, name);

        // TODO: test validations
    }
    /**
     * List
     *
     * List all payment
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void listPaymentTest() throws Exception {
        Integer limit = null;
        String lastKey = null;
        String name = null;
        InlineResponse2009 response = api.listPayment(limit, lastKey, name);

        // TODO: test validations
    }
    /**
     * Refund Payment
     *
     * Issue a refund for payment
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void refundPaymentTest() throws Exception {
        IssueRefundPayment body = null;
        String paymentId = null;
        api.refundPayment(body, paymentId);

        // TODO: test validations
    }
}
