/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.billabear.sdk.api;

import com.billabear.sdk.model.Error;
import com.billabear.sdk.model.InlineResponse20011;
import com.billabear.sdk.model.Price;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for PricesApi
 */
@Ignore
public class PricesApiTest {

    private final PricesApi api = new PricesApi();

    /**
     * Create
     *
     * Create a price
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createPriceTest() throws Exception {
        Price body = null;
        String productId = null;
        api.createPrice(body, productId);

        // TODO: test validations
    }
    /**
     * List
     *
     * List all prices
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void listPriceTest() throws Exception {
        String productId = null;
        Integer limit = null;
        String lastKey = null;
        InlineResponse20011 response = api.listPrice(productId, limit, lastKey);

        // TODO: test validations
    }
}
