/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.billabear.sdk.api;

import com.billabear.sdk.model.Error;
import com.billabear.sdk.model.InlineResponse20010;
import com.billabear.sdk.model.Product;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ProductsApi
 */
@Ignore
public class ProductsApiTest {

    private final ProductsApi api = new ProductsApi();

    /**
     * Create
     *
     * Create a product
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createProductTest() throws Exception {
        Product body = null;
        api.createProduct(body);

        // TODO: test validations
    }
    /**
     * List
     *
     * List all products
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void listProductTest() throws Exception {
        Integer limit = null;
        String lastKey = null;
        String name = null;
        InlineResponse20010 response = api.listProduct(limit, lastKey, name);

        // TODO: test validations
    }
    /**
     * Detail
     *
     * Info for a specific product
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void showProductByIdTest() throws Exception {
        String productId = null;
        Product response = api.showProductById(productId);

        // TODO: test validations
    }
    /**
     * Update
     *
     * Update a product
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateProductTest() throws Exception {
        String productId = null;
        Product response = api.updateProduct(productId);

        // TODO: test validations
    }
}
