/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.billabear.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.billabear.sdk.model.CheckoutItems;
import com.billabear.sdk.model.CheckoutSubscriptions;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * CheckoutBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-25T11:57:02.849979787Z[Etc/UTC]")

public class CheckoutBody {
  @SerializedName("name")
  private String name = null;

  @SerializedName("brand")
  private String brand = null;

  @SerializedName("slug")
  private String slug = null;

  @SerializedName("customer")
  private String customer = null;

  @SerializedName("items")
  private List<CheckoutItems> items = null;

  @SerializedName("subscriptions")
  private List<CheckoutSubscriptions> subscriptions = null;

  public CheckoutBody name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CheckoutBody brand(String brand) {
    this.brand = brand;
    return this;
  }

   /**
   * Get brand
   * @return brand
  **/
  @Schema(required = true, description = "")
  public String getBrand() {
    return brand;
  }

  public void setBrand(String brand) {
    this.brand = brand;
  }

  public CheckoutBody slug(String slug) {
    this.slug = slug;
    return this;
  }

   /**
   * Get slug
   * @return slug
  **/
  @Schema(description = "")
  public String getSlug() {
    return slug;
  }

  public void setSlug(String slug) {
    this.slug = slug;
  }

  public CheckoutBody customer(String customer) {
    this.customer = customer;
    return this;
  }

   /**
   * Get customer
   * @return customer
  **/
  @Schema(required = true, description = "")
  public String getCustomer() {
    return customer;
  }

  public void setCustomer(String customer) {
    this.customer = customer;
  }

  public CheckoutBody items(List<CheckoutItems> items) {
    this.items = items;
    return this;
  }

  public CheckoutBody addItemsItem(CheckoutItems itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<CheckoutItems>();
    }
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Get items
   * @return items
  **/
  @Schema(description = "")
  public List<CheckoutItems> getItems() {
    return items;
  }

  public void setItems(List<CheckoutItems> items) {
    this.items = items;
  }

  public CheckoutBody subscriptions(List<CheckoutSubscriptions> subscriptions) {
    this.subscriptions = subscriptions;
    return this;
  }

  public CheckoutBody addSubscriptionsItem(CheckoutSubscriptions subscriptionsItem) {
    if (this.subscriptions == null) {
      this.subscriptions = new ArrayList<CheckoutSubscriptions>();
    }
    this.subscriptions.add(subscriptionsItem);
    return this;
  }

   /**
   * Get subscriptions
   * @return subscriptions
  **/
  @Schema(description = "")
  public List<CheckoutSubscriptions> getSubscriptions() {
    return subscriptions;
  }

  public void setSubscriptions(List<CheckoutSubscriptions> subscriptions) {
    this.subscriptions = subscriptions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckoutBody checkoutBody = (CheckoutBody) o;
    return Objects.equals(this.name, checkoutBody.name) &&
        Objects.equals(this.brand, checkoutBody.brand) &&
        Objects.equals(this.slug, checkoutBody.slug) &&
        Objects.equals(this.customer, checkoutBody.customer) &&
        Objects.equals(this.items, checkoutBody.items) &&
        Objects.equals(this.subscriptions, checkoutBody.subscriptions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, brand, slug, customer, items, subscriptions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckoutBody {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    brand: ").append(toIndentedString(brand)).append("\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    customer: ").append(toIndentedString(customer)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    subscriptions: ").append(toIndentedString(subscriptions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
