/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Feature;
import io.swagger.client.model.Limit;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse2001
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-07-21T17:32:45.393056317Z[Etc/UTC]")

public class InlineResponse2001 {
  @SerializedName("limits")
  private List<Limit> limits = null;

  @SerializedName("features")
  private List<Feature> features = null;

  @SerializedName("user_count")
  private Integer userCount = null;

  public InlineResponse2001 limits(List<Limit> limits) {
    this.limits = limits;
    return this;
  }

  public InlineResponse2001 addLimitsItem(Limit limitsItem) {
    if (this.limits == null) {
      this.limits = new ArrayList<Limit>();
    }
    this.limits.add(limitsItem);
    return this;
  }

   /**
   * Get limits
   * @return limits
  **/
  @Schema(description = "")
  public List<Limit> getLimits() {
    return limits;
  }

  public void setLimits(List<Limit> limits) {
    this.limits = limits;
  }

  public InlineResponse2001 features(List<Feature> features) {
    this.features = features;
    return this;
  }

  public InlineResponse2001 addFeaturesItem(Feature featuresItem) {
    if (this.features == null) {
      this.features = new ArrayList<Feature>();
    }
    this.features.add(featuresItem);
    return this;
  }

   /**
   * Get features
   * @return features
  **/
  @Schema(description = "")
  public List<Feature> getFeatures() {
    return features;
  }

  public void setFeatures(List<Feature> features) {
    this.features = features;
  }

  public InlineResponse2001 userCount(Integer userCount) {
    this.userCount = userCount;
    return this;
  }

   /**
   * Get userCount
   * @return userCount
  **/
  @Schema(description = "")
  public Integer getUserCount() {
    return userCount;
  }

  public void setUserCount(Integer userCount) {
    this.userCount = userCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2001 inlineResponse2001 = (InlineResponse2001) o;
    return Objects.equals(this.limits, inlineResponse2001.limits) &&
        Objects.equals(this.features, inlineResponse2001.features) &&
        Objects.equals(this.userCount, inlineResponse2001.userCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(limits, features, userCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2001 {\n");
    
    sb.append("    limits: ").append(toIndentedString(limits)).append("\n");
    sb.append("    features: ").append(toIndentedString(features)).append("\n");
    sb.append("    userCount: ").append(toIndentedString(userCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
