/*
 * BillaBear
 * The REST API provided by BillaBear
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@billabear.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import java.io.File;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ReceiptApi
 */
@Ignore
public class ReceiptApiTest {

    private final ReceiptApi api = new ReceiptApi();

    /**
     * Download Receipt
     *
     * Returns the pdf blob for the Receipt
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void downloadReceiptTest() throws Exception {
        String receipt = null;
        File response = api.downloadReceipt(receipt);

        // TODO: test validations
    }
}
